// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'rotate': string;
  'search': string;
  'searchInput': string;
  'searchSvg': string;
  'searchSvgContainer': string;
  'shown': string;
  'spinner': string;
}
export const cssExports: CssExports;
export default cssExports;
