// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'next': string;
  'prev': string;
  'rotate': string;
  'shown': string;
  'slider': string;
  'sliderBox': string;
  'sliderButton': string;
  'sliderButtonArrow': string;
  'sliderSlides': string;
  'spinner': string;
}
export const cssExports: CssExports;
export default cssExports;
