// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'logo': string;
  'logoText': string;
  'subTitle': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
