// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'language': string;
  'languageAll': string;
  'languageAllLang': string;
  'languageCurrent': string;
  'languageCurrentLang': string;
  'rotate': string;
  'shown': string;
  'svg': string;
}
export const cssExports: CssExports;
export default cssExports;
