// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'info': string;
  'infoText': string;
  'language': string;
  'languageAll': string;
  'languageAllLang': string;
  'languageCurrent': string;
  'languageCurrentLang': string;
  'logo': string;
  'logoText': string;
  'navBar': string;
  'navBarContent': string;
  'navBarControls': string;
  'rotate': string;
  'search': string;
  'searchError': string;
  'searchInput': string;
  'searchResults': string;
  'searchResultsItem': string;
  'searchResultsWrapper': string;
  'searchSvg': string;
  'shown': string;
  'subTitle': string;
  'svg': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
