// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'added': string;
  'disabled': string;
  'goodCard': string;
  'goodCardAdd': string;
  'goodCardDiscountUntil': string;
  'goodCardImage': string;
  'goodCardPricePerKilo': string;
  'goodCardTextWrapper': string;
  'goodCardTitle': string;
  'info': string;
  'infoDiscount': string;
  'infoMarket': string;
  'prices': string;
  'pricesCurrent': string;
  'pricesOld': string;
  'rotate': string;
  'spinner': string;
}
export const cssExports: CssExports;
export default cssExports;
